export const eventId = 104;

export const organizerId = 5;

export const chatlioWidgetId = "027e5aa4-7949-4be7-63d5-515e44e16add";

export const visitorTicketId = 3175;

export const basePriceCurrency = "EUR";

export const pricesNetGross = "net";

export const GTM_ID = "GTM-5RJC4J" //"GTM-P3VS4G8P"

export const baseUrl = process.env.NODE_ENV === "production" ? `${process.env.NEXT_PUBLIC_BASE_URL}`: "https://legible-key-frog.ngrok-free.app"

export const blockedEmailDomains = [
    "@gmail.com",
    "@web.de",
    "@gmx.net",
    "@live.com",
    "@mail.ru",
    "@gmx.de",
    "@hotmail.com",
    "@outlook.com",
    "@icloud.com",
    "@t-online.de",
    "@wp.pl",
    "@yahoo.pl",
    "@me.com",
    "@yahoo.com",
    "@yahoo.de",
    "@live.com",
    "@mail.ru",
    "@list-manage.com",
    "@web.de",
    "@gmx.net",
    "@hotmail.com",
    "@sendgrid.net",
    "@evite.com",
    "@live.net",
    "@1drv.ms",
    "@szn.cz",
    "@linkedinmobileapp.com",
    "@mailchimp.com",
    "@mailchi.mp",
    "@temp-mail.org",
    "@mail.com",
    "@freemail.hu",
    "@mimecast.com",
    "@liveinternet.ru",
    "@families.google",
    "@126.com",
    "@mlsend.com",
    "@cmail20.com",
    "@cmail19.com",
    "@campaign-archive.com",
    "@webmail.free.fr",
    "@gmx.ch",
    "@posteo.de",
    "@kpnmail.nl",
    "@hao6v.tv",
    "@gmx.com",
    "@fastmail.com",
    "@cehennempass.pw",
    "@yahoomail.com",
    "@mail.ee",
    "@hushmail.com",
    "@dripemail2.com",
    "@convertkit-mail2.com",
    "@greetingsisland.com",
    "@tegos.club",
    "@gmx.fr",
    "@deref-mail.com",
    "@instantly.ai",
    "@cybermail.jp",
    "@ymail.com",
    "@mail.de",
    "@networksolutionsemail.com",
    "@outlook.de",
    "@live.de",
    "@mac.com",
    "@googlemail.com",
    "@live.fr",
    "@outlook.pt",
    "@mds.eu",
    "@live.nl",
    "@live.co.uk",
    "@hotmail.it",
    "@hotmail.fr",
    "@hotmail.de",
    "@hotmail.co.uk",
    "@gmx.org",
    "@mailbox.org",
    "@yandex.com",
    "@yandex.ru",
    "@yahoo.co.in",
    "@yahoo.co.uk",
    "@yahoo.com.br",
    "@yahoo.com.hk",
    "@yahoo.com.tr",
    "@yahoo.dk",
    "@yahoo.es",
    "@yahoo.fr",
    "@yahoo.gr",
    "@yahoo.in",
    "@yahoo.ro",
    "@yahoo.se",
    "@vp.pl",
    "@post.ba",
    "@post.cz",
    "@post.pl",
    "@o2.pl",
    "@op.pl",
    "@aol.com",
    "@aol.de",
    "@icloud.com"
  ];
  